version: '3'
services:
  crawling:
    container_name: crawling-server
    build:
      context: ./crawling_server
      dockerfile: Dockerfile
    image: shortgong_crawling:latest
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - fastapi

networks:
  fastapi:


