version: '3'
services:
  backend:
    container_name: back-server
    build:
      context: ./server/shortgong
      dockerfile: Dockerfile
    image: shortgong_backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./server/shortgong/.env
    environment:
      - TZ=Asia/Seoul
    networks:
      - shortgong

  crawling:
    container_name: crawling-server
    build:
      context: ./crawling_server
      dockerfile: Dockerfile
    image: shortgong_crawling:latest
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - shortgong

  frontend:
    container_name: front-client
    build:
      context: ./front
      dockerfile: Dockerfile
    image: shortgong_frontend:latest
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - shortgong

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/data/certbot/www:/var/www/certbot
    networks:
      - shortgong

  certbot:
    image: certbot/certbot
    volumes:
      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  shortgong:


