server:
  port: ${BACK_PORT}

logging:
  level:
    root: info
    com.ssafy.a304.shortgong.domain: debug

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: shortgong

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DOMAIN}:3306/${SCHEMA_NAME}?serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
        ddl-auto: ${JPA_DDL_AUTO_OPTION}
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: ${JPA_SHOW_SQL_OPTION}
    open-in-view: false

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  data:
    redis:
      host: ${DOMAIN}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

cors:
  allowedOrigins: ${PROTOCOL}://${DOMAIN}:${FRONT_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

expire-time:
  redis-access-token: 14400
  jwt-access-token: 36000000
  jwt-refresh-token: 604800000

cloud:
  aws:
    s3:
      bucket: a304-storage
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      url: ${CLOUDFRONT_URL}

file:
  path:
    user-profile-folder: user
    summary-folder: summary
